$mainMod = SUPER

$terminal = ghostty
$menu = wofi --show drun

monitor = , preferred, auto, 1

exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent

input {
    kb_layout = us
    follow_mouse = 1

    touchpad = {
        natural_scroll = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8

    border_size = 2

    layout = dwindle
}

decoration {
    rounding = 8
}

animations {
    enabled = true
}

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, D, exec, $menu

bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, E, exit

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
