autoload -Uz compinit
compinit

setopt AUTO_CD
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

bindkey -e

export EDITOR=nvim
export VISUAL=nvim

alias ll='ls -lah'